#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "schemas" / "satchel.schema.json"
REFERENCE_PATH = ROOT / "docs" / "schema-reference.md"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate Satchel schema reference docs.")
    parser.add_argument("--check", action="store_true", help="fail if generated docs are stale")
    args = parser.parse_args(argv)

    content = render_reference(load_schema(SCHEMA_PATH))
    if args.check:
        current = REFERENCE_PATH.read_text(encoding="utf-8") if REFERENCE_PATH.exists() else ""
        if current != content:
            print(f"stale generated docs: {REFERENCE_PATH}", file=sys.stderr)
            return 1
        return 0

    REFERENCE_PATH.write_text(content, encoding="utf-8")
    print(f"generated {REFERENCE_PATH.relative_to(ROOT)}")
    return 0


def load_schema(path: Path) -> dict[str, Any]:
    parsed = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(parsed, dict):
        raise TypeError("schema root must be an object")
    return parsed


def render_reference(schema: dict[str, Any]) -> str:
    required_fields = ", ".join(f"`{field}`" for field in schema.get("required", []))
    lines = [
        "# `satchel.yaml` Schema Reference",
        "",
        "<!-- Generated by scripts/generate_schema_docs.py. Do not edit by hand. -->",
        "",
        schema.get("description", "Satchel manifest schema."),
        "",
        f"- Schema ID: `{schema.get('$id', '<missing>')}`",
        f"- Required root fields: {required_fields}",
        "",
        "## Root Fields",
        "",
    ]
    lines.extend(
        _field_table(
            schema.get("properties", {}),
            required=set(schema.get("required", [])),
            exclude={"components", "targets"},
        )
    )
    lines.extend(["", "## Components", ""])
    lines.extend(_field_table(_properties(schema, "components")))
    lines.extend(["", "## Targets", ""])
    lines.extend(_field_table(_properties(schema, "targets")))
    lines.extend(["", "## Target Fields", ""])
    lines.extend(_field_table(_definition_properties(schema, "target"), required=set()))
    lines.extend(["", "## Marketplace Fields", ""])
    lines.extend(_field_table(_marketplace_properties(schema), required=set()))
    lines.append("")
    return "\n".join(lines)


def _field_table(
    properties: dict[str, Any],
    *,
    required: set[str] | None = None,
    exclude: set[str] | None = None,
) -> list[str]:
    required = required or set()
    exclude = exclude or set()
    lines = [
        "| Field | Required | Type | Description |",
        "| --- | --- | --- | --- |",
    ]
    for name, field in properties.items():
        if name in exclude or not isinstance(field, dict):
            continue
        lines.append(
            "| "
            f"`{name}` | "
            f"{'yes' if name in required else 'no'} | "
            f"{_type_label(field)} | "
            f"{_description(field)} |"
        )
    return lines


def _properties(schema: dict[str, Any], name: str) -> dict[str, Any]:
    value = schema.get("properties", {}).get(name, {}).get("properties", {})
    return value if isinstance(value, dict) else {}


def _definition_properties(schema: dict[str, Any], name: str) -> dict[str, Any]:
    value = schema.get("$defs", {}).get(name, {}).get("properties", {})
    return value if isinstance(value, dict) else {}


def _marketplace_properties(schema: dict[str, Any]) -> dict[str, Any]:
    target = schema.get("$defs", {}).get("target", {})
    value = target.get("properties", {}).get("marketplace", {}).get("properties", {})
    return value if isinstance(value, dict) else {}


def _type_label(field: dict[str, Any]) -> str:
    if "const" in field:
        return f"`{field['const']}`"
    if "$ref" in field:
        return f"`{field['$ref'].split('/')[-1]}`"
    if "oneOf" in field:
        types = [_type_label(option) for option in field["oneOf"] if isinstance(option, dict)]
        return " or ".join(types)
    raw_type = field.get("type")
    if isinstance(raw_type, list):
        return " or ".join(f"`{item}`" for item in raw_type)
    if isinstance(raw_type, str):
        return f"`{raw_type}`"
    return "`object`"


def _description(field: dict[str, Any]) -> str:
    description = str(field.get("description", "")).strip()
    default = field.get("default")
    examples = field.get("examples")
    parts = [description] if description else []
    if default is not None:
        parts.append(f"Default: `{json.dumps(default)}`.")
    if isinstance(examples, list) and examples:
        parts.append(f"Example: `{json.dumps(examples[0])}`.")
    return _escape_pipes(" ".join(parts) or "-")


def _escape_pipes(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


if __name__ == "__main__":
    raise SystemExit(main())
